CREATE TABLE Reader
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(200)                  NOT NULL UNIQUE,
    birthYear int CHECK (birthyear >= 1900) NOT NULL
);

CREATE TABLE Book
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(100) NOT NULL,
    author     varchar(100) NOT NULL,
    year       int          NOT NULL,
    issue_date timestamp,
    reader_id  int          REFERENCES Reader (id) ON DELETE SET NULL
);

INSERT INTO Reader(name, birthYear)
VALUES ('Брюс Уиллис', 1955);
INSERT INTO Reader(name, birthYear)
VALUES ('Киану Ривз', 1964);
INSERT INTO Reader(name, birthYear)
VALUES ('Кейт Уинслет', 1975);
INSERT INTO Reader(name, birthYear)
VALUES ('Клэр Форлани', 1971);
INSERT INTO Reader(name, birthYear)
VALUES ('Джейк Джилленхол', 1980);

INSERT INTO Book(title, author, year)
VALUES ('Преступление и наказание', 'Фёдор Михайлович Достоевский', 1866);
INSERT INTO Book(title, author, year)
VALUES ('Трудно быть богом', 'Аркадий и Борис Стругацкие', 1964);
INSERT INTO Book(title, author, year)
VALUES ('Отцы и дети', 'Иван Тургенев', 1862);
INSERT INTO Book(title, author, year)
VALUES ('Обломов', 'Иван Гончаров', 1859);
INSERT INTO Book(title, author, year)
VALUES ('Анна Каренина', 'Лев Толстой', 1877);
INSERT INTO Book(title, author, year)
VALUES ('Двенадцать стульев', 'Илья Ильф и Евгений Петров', 1928);
INSERT INTO Book(title, author, year)
VALUES ('Мастер и Маргарита', 'Михаил Булгаков', 1966);
INSERT INTO Book(title, author, year)
VALUES ('Собачье сердце', 'Михаил Булгаков', 1925);
INSERT INTO Book(title, author, year)
VALUES ('Тихий Дон', 'Михаил Шолохов', 1940);
INSERT INTO Book(title, author, year)
VALUES ('To Kill a Mockingbird', 'Harper Lee', 1960);
INSERT INTO Book(title, author, year)
VALUES ('1984', 'George Orwell', 1949);
INSERT INTO Book(title, author, year)
VALUES ('Brave New World', 'Aldous Huxley', 1932);
INSERT INTO Book(title, author, year)
VALUES ('The Lord of the Rings', 'J.R.R. Tolkien', 1954);
INSERT INTO Book(title, author, year)
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1925);
INSERT INTO Book(title, author, year)
VALUES ('Pride and Prejudice', 'Jane Austen', 1813);
INSERT INTO Book(title, author, year)
VALUES ('Frankenstein', 'Mary Shelley', 1818);
INSERT INTO Book(title, author, year)
VALUES ('Little Women', 'Louisa May Alcott', 1868);

